[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "aarch64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
  { triple = "aarch64-unknown-linux-musl" },
  { triple = "x86_64-apple-darwin" },
  { triple = "aarch64-apple-darwin" },
  { triple = "x86_64-pc-windows-msvc" },
  { triple = "aarch64-pc-windows-msvc" },
]

[advisories]
git-fetch-with-cli = true
ignore = ["RUSTSEC-2024-0320"]

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "Zlib",
  "ISC",
  "BSD-3-Clause",
  "MPL-2.0",
]
exceptions = [
  { allow = [
    "Unicode-DFS-2016",
  ], name = "unicode-ident" },
  { allow = [
    "BSL-1.0",
  ], name = "clipboard-win" },
  { allow = [
    "BSL-1.0",
  ], name = "error-code" },
  { allow = [
    "BSL-1.0",
  ], name = "str-buf" },
  { allow = [
    "MIT",
    "ISC",
    "OpenSSL",
  ], name = "ring" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
